### ISSUE TITLE
[Bug/Feature] 后台管理问题

### ISSUE THREAD

**Issue by Axerli** [dadi-cn/poppy-mgr-app#3]
```bash
poppy/mgr-app                           4.0.x-dev 579f7ab An form support module for poppy sep system
poppy/mgr-page                          4.0.x-dev 483d238 An admin management page module.

```

### Description

- [x] 1. 后台管理系统配置，类型检测错误

<img width="769" alt="image" src="https://user-images.githubusercontent.com/9879953/168757699-7cb6cb67-3cd4-4fac-aba8-5547d10e0ea6.png">

- [x] 2. 图片类型组件不能正常显示

<img width="674" alt="image" src="https://user-images.githubusercontent.com/9879953/168758836-34c5deec-d583-4c1a-aeaa-fb8ba49eb5d5.png">

- [x] 3. 账号管理-修改密码页面, `tab` 键不能使用
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/9879953/168762076-bd6c9a08-d514-4988-9c18-634d1ba2eb02.png">

- [x] 4. 操作没有提示语
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/9879953/168763215-9b6c88fb-fba3-4dd4-8429-af7e39bf1304.png">

- [x] 5. 地区管理编辑 500错误
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/9879953/168763936-54c83a4a-8f85-4569-98a2-cd2d67ed1e78.png">

- [x] 6. 短息模板删除按钮点击无响应
操作步骤：
```
1. 点击删除按钮
2. 出现弹窗后，关闭弹窗
3. 再次点击删除按钮无响应
```

**Comment by Axerli** [comment]
- [ ] 7. token过期，未跳转到登录页面
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/9879953/168936572-4e70348c-bf29-4df8-b2eb-b3fc35f0d97c.png">

**Comment by Axerli** [comment]
- [ ] 9. 列表页增加排序功能

<img width="228" alt="image" src="https://user-images.githubusercontent.com/9879953/171089059-ef0aadf4-4243-4101-891c-635bb18bd7c1.png">

**Comment by Axerli** [comment]
- [ ] 13. timeRange 组件错误
- [ ] 14. 多层表单支持
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/9879953/172977026-833fbdca-c080-4056-a9b0-7c7b5f3b0303.png">

**Comment by imvkmark** [comment]
更新位置, 此 issue 关闭
